repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt

  # TODO: resolve caveats before enabling: https://github.com/gruntwork-io/pre-commit?tab=readme-ov-file#helm-lint-caveats
  # - repo: https://github.com/gruntwork-io/pre-commit
  #   rev: v0.1.22
  #   hooks:
  #     - id: helmlint

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=helm-charts
          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl
          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
