name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"
      - ".github/workflows/helm-test.yaml"
      - ".github/workflows/helm-release.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      CT_CHART_DIRS: helm-charts
      CT_CHECK_VERSION_INCREMENT: false
      CT_TARGET_BRANCH: ${{ github.event.repository.default_branch }}
      CT_VALIDATE_MAINTAINERS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # - name: Run pre-commit
      #   run: |
      #     pip install pre-commit
      #     pre-commit run --all-files
      #   env:
      #     SKIP: no-commit-to-branch

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        run: ct lint

    #   - name: Create kind cluster
    #     uses: helm/kind-action@v1.8.0

    #     # TODO: do what they did here and pass in --config
    #     # https://github.com/prometheus-community/helm-charts/actions/runs/6342491434/workflow#L48
    #   - name: Run chart-testing (install)
    #     run: ct install
