name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/workflows/helm-release.yaml"

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get app token
        uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.GITOPS_APP_ID }}
          private-key: ${{ secrets.GITOPS_APP_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          # https://api.github.com/users/dominic-gitops%5Bbot%5D
          git config user.name dominic-gitops[bot]
          git config user.email 146885307+dominic-gitops[bot]@users.noreply.github.com
          git config credential.https://github.com.username dominic-gitops[bot]

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      - name: Run chart-releaser
        # TODO: use 1.6.0 when released for this: https://github.com/helm/chart-releaser-action/issues/162
        # uses: helm/chart-releaser-action@v1.6.0
        uses: helm/chart-releaser-action@ed43eb303604cbc0eeec8390544f7748dc6c790d
        with:
          skip_existing: true
        env:
          CR_TOKEN: ${{ steps.token.outputs.token }}
          CR_GENERATE_RELEASE_NOTES: true
          CR_OWNER: ${{ github.repository_owner }}
          CR_GIT_REPO: ${{ github.repository }}
          CR_INDEX_PATH: .

      # see https://github.com/helm/chart-releaser/issues/183
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"
          done
